[package]
name = "tok_staking"
edition = "2024"         # edition = "legacy" to use legacy (pre-2024) Move
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
tok_fees = { local = "../tok_fees" }

[addresses]
tok_staking = "0x0"
tok_fees = "0x21dee5942c2b9198f46c846bd16c854c2d0f4b7bb13a2efb66172ac71deb40e6"

# Read more about the package management system options:
# https://docs.sui.io/guides/developer/sui-101/move-package-management
